### ISSUE TITLE
cross-browser keycodes?

### ISSUE THREAD

**Issue by miketaylr** [wesbos/keycodes#1]
As you might imagine, browsers are terrible. Left Cmd key on OSX, for example is 224 in Firefox. But that's not in your keycode map, so you just get the keyCode but the text doesn't update.

See http://unixpapa.com/js/key.html.

**Comment by palashmon** [comment]
Closing this issue for now. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this or open a new one. We'll gladly take a look again!
