### ISSUE TITLE
` quotes in .onkeydown don't work

### ISSUE THREAD

**Issue by Onedy** [wesbos/keycodes#103]
Chrome 40.0.2214.91, Windows 7.

scripts.js:170 Uncaught SyntaxError: Unexpected token ILLEGAL

``huh? Let me know what browser and key this was. <a href='https://github.com/wesbos/keycodes/issues/new?title=Missing keycode ${e.keyCode}&body=Tell me what key it was or even better, submit a Pull request!'>Submit to Github</a>`;

It works with double quotes:
`"huh? Let me know what browser and key this was. <a href='https://github.com/wesbos/keycodes/issues/new?title=Missing keycode ${e.keyCode}&body=Tell me what key it was or even better, submit a Pull request!'>Submit to Github</a>";`

**Comment by palashmon** [comment]
Not able to reproduce the issue at the moment. If anyone else is getting similar issues then please let me know. I will then re-open the issue again.

Regards!
