### ISSUE TITLE
Missing keycode 252

### ISSUE THREAD

**Issue by joshrencher** [wesbos/keycodes#117]
I wish I could tell you what key this is, but it fires automatically every 10 seconds on the dot - regardless of browser. Appreciate your tool for helping me confirm this.

**Comment by 8000ice** [comment]
That's got to be the weirdest thing I've ever heard of. What keyboard and computer is it?? It's probably the computer doing it if it's every ten seconds on the dot like you said.

**Comment by joshrencher** [comment]
So you waited a year and 9+ months to address this issue, and your response was to mark it "invalid" and close it without resolution? Got it. Thanks.

**Comment by wesbos** [comment]
Sorry the issues have got away from me and I’m just getting help - no one else has reported this so it’s likely an issue with your hardware. Let me know if you get any closer on defining the issue

**Comment by joshrencher** [comment]
Thanks for the quick reply. Now I'm sorry for being snarky! :)

I do agree that it's most likely a local hardware issue, but I believe I
created the issue because whatever keystroke was firing mysteriously was
being detected as an "unknown" by your system. I figured you might have
some way of logging andf identifying it if I made you aware. No big deal,
if not. Thank you again.

Josh
