### ISSUE TITLE
Missing keycode 0

### ISSUE THREAD

**Issue by csskevin** [wesbos/keycodes#118]
Hey,
I have a calculator button on my keybord (Microsoft Sidewinder x4).
https://img.conrad.de/medias/global/ce/9000_9999/9000/9070/9079/907987_BB_00_FB.EPS.jpg
(Above the Numlock button)
KeyCode: 183
(C# says as Value: LaunchApplication2)

I hope it's useful ^^

**Comment by wesbos** [comment]
Hey - thanks a lot. Keycode 0 means there is no keyCode associated with that key. I will update the app to reflect that.
