### ISSUE TITLE
Missing keycode 0

### ISSUE THREAD

**Issue by aleks-romanich** [wesbos/keycodes#121]
Tell me what key it was or even better, submit a Pull request!
1. OS - Ubuntu 16.04
2. Browser Firefox 49
3. keys - "б ю ж э х ъ ё" in russian keyboard (cyrillic alphabet)

**Comment by wesbos** [comment]
Hey - thanks a lot. Keycode 0 means there is no keyCode associated with that key. I will update the app to reflect that.
