### ISSUE TITLE
Missing keycode 0

### ISSUE THREAD

**Issue by johanvdp** [wesbos/keycodes#129]
Tell me what key it was or even better, submit a Pull request!
A key on my laptop, second row, 1st left
row 1: esc f1 f2 ...
row 2: [(normal) ` or (shift) ~]  1 2 3 ...
row 3: tab q w e ...

**Comment by wesbos** [comment]
Hey - thanks a lot. Keycode 0 means there is no keyCode associated with that key. I will update the app to reflect that.
