### ISSUE TITLE
Right Ctrl (225)

### ISSUE THREAD

**Issue by marinintim** [wesbos/keycodes#13]
When I press right Ctrl, it shows 225 and that it doesn't know this key.

Yandex.Browser, Ubuntu.

**Comment by wesbos** [comment]
Thanks for reporting it - What Language is your keyboard?

**Comment by marinintim** [comment]
@wesbos Russian.

**Comment by palashmon** [comment]
It seems that keycode `225` was added later on:

https://github.com/wesbos/keycodes/blob/gh-pages/scripts.js#L161

Please check once and re-open the issue is still not fixed.

Regards!
