### ISSUE TITLE
Missing keycode 0

### ISSUE THREAD

**Issue by antongustafsson** [wesbos/keycodes#147]
Fn + PowerKey on Mac
[Fn-key](https://markwagner1.files.wordpress.com/2011/01/mac20fn20function.png)
[Power-key](http://ddproductions.ga/lhspodcast/img/power.png)

**Comment by wesbos** [comment]
Hey - thanks a lot. Keycode 0 means there is no keyCode associated with that key. I will update the app to reflect that.
