### ISSUE TITLE
English and non-English letters with the same key in the keyboard have the same keyCode

### ISSUE THREAD

**Issue by Ahed91** [wesbos/keycodes#156]
Sorry about my (poor) English

OS: Ubuntu 14.04 with two keyboard layouts (ar, en)
Browser: Firefox 53.0a , Chrome 53.0.2785.89

This is event object when pressing `a` in Chrome
    
    altKey: false
    bubbles: true
    cancelBubble: false
    cancelable: true
    charCode: 0
    code: "KeyA"
    composed: true
    ctrlKey: false
    currentTarget: null
    defaultPrevented: true
    detail: 0
    eventPhase: 0
    isTrusted: true
    key: "a"
    keyCode: 65
    keyIdentifier: "U+0041"
    location: 0
    metaKey: false
    path: Array[4]
    repeat: false
    returnValue: false
    shiftKey: false
    sourceCapabilities: InputDeviceCapabilities
    srcElement: body
    target: body
    timeStamp: 1674.19
    type: "keydown"
    view: Window
    which: 65

when press `ش` (Sheen is Arabic Alphabet letter shares the same key in the keyboard with "a")

    altKey: false
    bubbles: true
    cancelBubble: false
    cancelable: true
    charCode: 0
    code: "KeyA"
    composed: true
    ctrlKey: false
    currentTarget: null
    defaultPrevented: true
    detail: 0
    eventPhase: 0
    isTrusted: true
    key: "ش"
    keyCode: 65
    keyIdentifier: "U+0041"
    location: 0
    metaKey: false
    path: Array[4]
    repeat: false
    returnValue: false
    shiftKey: false
    sourceCapabilities: InputDeviceCapabilities
    srcElement: body
    target: body
    timeStamp: 6391.1900000000005
    type: "keydown"
    view: Window
    which: 65

the difference between them is 

    key: "a"    key: "ش"
    timeStamp: 1674.19    timeStamp: 6391.1900000000005

So .. in order to use key names defined in the browser I replaced  [line 170-171](https://github.com/wesbos/keycodes/blob/31805003be6614934f993c2fe774665f8f25ffc0/scripts.js#L170)

    document.querySelector('.text-display').innerHTML =
    keyCodes[e.keyCode] || "huh? Let me know what browser and key this was. <a href=\"https://github.com/wesbos/keycodes/issues/new?title=Missing keycode ${e.keyCode}&body=Tell me what key it was or even better, submit a Pull request!\">Submit to Github</a>";

with 

    document.querySelector('.text-display').innerHTML = e.key;

![keycodes_issue-fs8](https://cloud.githubusercontent.com/assets/4216500/22616197/0e9bb5a8-eab1-11e6-9afa-6af4eed05d4b.png)

I believe we should use `e.key` as fallback e.g. `keyCodes[e.keyCode] || e.key` and just use `keyCodes` just to fix browsers compatibility ,e.g. key code 91 is meta in chrome and OS in firefox , and provide more friendly names when necessary.

**Comment by palashmon** [comment]
Thanks for reporting this and your suggestions. `keycode` is same since `keyCode` says something about the actual keyboard key the user pressed. For instance, a lower case 'a' and an upper case 'A' have the same keyCode, because the user presses the same key.

More info on it [here](https://www.quirksmode.org/js/keys.html)

Also, check out the updated site and let us know your response. Closing this issue for now.
