### ISSUE TITLE
Plus sign

### ISSUE THREAD

**Issue by idleberg** [wesbos/keycodes#16]
When I hit <kbd>+</kbd>, it detect <kbd>=</kbd> instead

**Comment by wesbos** [comment]
That is because it's the same key - the `+` is a modifier when you press shift and hit `=`.

I've had a few people ask for this functionality though so I may add it in.

**Comment by idleberg** [comment]
I was wondering about that, especially since other tools like yours produced the same result. I didn't think of what you said, since I'm not using a US keyboard layout and I got seperate keys for those.

**Comment by wesbos** [comment]
Ah yes - which keyboard do you have? 

I do need some sort of plan for internationalization as well..

**Comment by idleberg** [comment]
I'm typing this on an Apple keyboard with German layout (QWERTZ)
