### ISSUE TITLE
Missing keycode & 10 more bugs

### ISSUE THREAD

**Issue by my4n1** [wesbos/keycodes#166]
1.  start page-button
2. "open music programm" button

3. "semi-colon / ñ" is also the "ü" on the german keyboard
4. "grave accent / ñ / æ" is also "ö"
5. "single quote / ø" is also "ä"
6.  ^  is called "back slash"
7.  ß  is called "open bracket"
8.  ´  is called "close bracket / å"
9.  "pos1" is called there "home"
10. the ? key is called "Windows Key / Left ⌘ / Chromebook Search key"
11. the + key is called "equal sign"
12. the # key is called "forward slash / ç"

for all this I used Chrome browser on windows 10 with a german keyboard

I hope i could help you and my english wasn't too bad :)

**Comment by palashmon** [comment]
Hi, thanks for reporting this. The site has been updated. Could you please check if the issue still exists and let us know your response. Closing this for now.

Regards!
