### ISSUE TITLE
Missing keycode 21 and 25

### ISSUE THREAD

**Issue by hieroglyphic** [wesbos/keycodes#168]
- [21: <kbd>한/영</kbd> or right <kbd>Alt</kbd>](https://en.wikipedia.org/wiki/Language_input_keys#Han.2FYeong_.28.ED.95.9C.2F.EC.98.81.29)
- [25: <kbd>한자</kbd> or right <kbd>Ctrl</kbd>](https://en.wikipedia.org/wiki/Language_input_keys#Hanja_.28.ED.95.9C.EC.9E.90.29)
---
UA: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36`

**Comment by palashmon** [comment]
Fixed in PR #153
