### ISSUE TITLE
Google Chrome 43. Keypress: `¬¦ resulted in 223 huh? Let me know what browser and key this was.

### ISSUE THREAD

**Issue by AshleyWright** [wesbos/keycodes#17]
Browser: Google Chrome 43.0.2357.132 (Official Build) m (32-bit)
Operating System: Windows 8.1
Keyboard: English (UK) QWERTY Keyboard.

The key pressed appears at the top left of keyboard under the Esc key, that what pressed prints characters: &#96;, (shift) `¬`, (alt gr) `¦`.

**Comment by palashmon** [comment]
Going to close this issue, as I think this is fixed now for keycode `223`.

https://github.com/wesbos/keycodes/blob/gh-pages/scripts.js#L159

Please re-open if you think otherwise.
