### ISSUE TITLE
Turkish characters all missing

### ISSUE THREAD

**Issue by HarunKARATAS** [wesbos/keycodes#172]
![trch](https://cloud.githubusercontent.com/assets/7129948/24102160/b5fc603c-0d83-11e7-8091-45812daf500f.png)
 
These are Turkish characters and missing . For more information you can find in here [https://www.ascii-codes.com/cp857.html](click) . In extended character set.

**Comment by palashmon** [comment]
Hi, thanks for reporting this. The site has been updated. Could you please check if the issue still exists and let us know your response.

Regards!

**Comment by palashmon** [comment]
Closing this issue for now. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this or open a new one. We'll gladly take a look again!
