### ISSUE TITLE
- and = sign on Firefox

### ISSUE THREAD

**Issue by TimohStudios** [wesbos/keycodes#18]
Running the latest version of Firefox on Windows 10, US International keyboard layout, pressing the `-` (minus and underscore) key tells me "`173` mute/unmute". The proper key for this, which in the case of my laptop is `Fn + F8` does display as "`181` mute/unmute (firefox)". The `=` (equals and plus) key is not recognized, keycode is `61`.

**Comment by TimohStudios** [comment]
Little addition, the `;` (semicolon) is also not recognized, keycode `59`, same environment.

**Comment by Mazuh** [comment]
Dunno why is this happening, but there's the same issue at firefox for updated linux mint here. So I tried to fix it in a flexible way.
