### ISSUE TITLE
Missing keycode for Compose key

### ISSUE THREAD

**Issue by bmintz** [wesbos/keycodes#187]
When I press my Compose key on Ubuntu 17.04, I get keycode 0 and "huh"?

**Comment by palashmon** [comment]
Hi, thanks for reporting this. The site has been updated. Could you please check if the issue still exists and let us know your response.

Regards!

**Comment by palashmon** [comment]
Closing this issue for now. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this or open a new one. We'll gladly take a look again!
