### ISSUE TITLE
Key not registering

### ISSUE THREAD

**Issue by hauntid** [wesbos/keycodes#189]
Quite a few laptops have FuNction key or `fn` for short. This does not seem to register.

**Comment by ted537** [comment]
This is a browser level issue - event.keycode is 0 for the fn key, which means it can't be identified

**Comment by palashmon** [comment]
The `Fn` key does not have a scan code.

The keyboard driver does not expose the `Fn` key to the operating system so basically, your operating system does not know that it exists.

When you press the `Fn` key in combination with a supported key, the keyboard driver reports a single key press to the operating system with a different scan code. Basically, it tells the operating system that a different key was pressed.
