### ISSUE TITLE
LMKWBAKTW Media Control Buttons

### ISSUE THREAD

**Issue by mattman00000** [wesbos/keycodes#19]
Chrome Version 46.0.2490.64 beta-m (64-bit)

179 - Play/Pause ( >|| )
178 - Stop ( [] )
177 - Previous ( |<< )
176 - Next ( >>| )

**Comment by wesbos** [comment]
Mind sending in a PR? Just add them to the JS object

**Comment by mattman00000** [comment]
done, I think. still relatively new to pull requests.

**Comment by wesbos** [comment]
Thanks! Added.
