### ISSUE TITLE
Missing keycode 241

### ISSUE THREAD

**Issue by TichShowers** [wesbos/keycodes#192]
Tell me what key it was or even better, submit a Pull request!

When Switching mode on Windows IME Keyboard for Japanese. (Pressing of ALT + CAPS LOCK) brings up keycode 241.

**Comment by onkbear** [comment]
@TichShowers
keycode 241 is `Alt + Hiragana/Katakana` on my 109 japanese keyboard.
It is used to switch to katakana characters.

I think `241 : "katakana"` is better.

**Comment by palashmon** [comment]
Hi, thanks for reporting this. The site has been updated. Could you please check if the issue still exists and let us know your response. Closing this for now.

Regards!
