### ISSUE TITLE
keyup & keydown VS keypress

### ISSUE THREAD

**Issue by mmason33** [wesbos/keycodes#195]
Character codes seem to differentiate depending on the given keyboard event. I ran into this issues recently on a project. I am having trouble finding specific documentation on this issue. I believe (again I am not sure and may be wrong) keypress includes: alphanumeric, enter, shift and ctrl - keyup,keydown includes: every key. In my tests, keypress delivers a = 97 and keyup a = 65.
![65](https://user-images.githubusercontent.com/22351595/27613233-520794e2-5b4f-11e7-8a25-257c3af4913f.PNG)
![97](https://user-images.githubusercontent.com/22351595/27613237-55098e8e-5b4f-11e7-9536-580aba335127.PNG)

I just thought I would mention this to you. I really appreciate this project and wanted to help if possible. Feel free to close this issue accordingly. Again everything I've outlined above is my understanding at this time. I'm open to corrections, criticism and feedback. I'm always learning! Thank you.

**Comment by palashmon** [comment]
Closing this issue for now, as a similar issue related to this has not been reported so far. But we might re-open it again if needed.

Thanks for your time and thoughts on this!
