### ISSUE TITLE
No proper Emoji support

### ISSUE THREAD

**Issue by whackcat** [wesbos/keycodes#203]
Type an emoji into Firefox and the rest an unknown character message will pop up but on Google Chrome an emoji comes up as this in the screenshot. Note that this is on Windows 10 64-bit.
![2017_07_25_16_20_47_javascript_event_keycodes](https://user-images.githubusercontent.com/16402684/28580256-de51c02c-7156-11e7-9852-af6086125e9d.png)

**Comment by wesbos** [comment]
There are no keyboards with emoji - are there?

**Comment by whackcat** [comment]
Windows 8 and newer have keyboards with emoji included onscreen - see this: 
![image](https://user-images.githubusercontent.com/16402684/31587839-90e2eea4-b1e0-11e7-9e28-7df07b4b5b73.png)

**Comment by whackcat** [comment]
Just realized - emoji do not send actual keycodes.
