### ISSUE TITLE
Missing keycode 0

### ISSUE THREAD

**Issue by Rogergonzalez21** [wesbos/keycodes#206]
Tell me what key it was or even better, submit a Pull request!

Missing key "ñ"

**Comment by gerbosan** [comment]
Have same problem with the letter "ñ". Tried with Firefox 52.3.0 in Linux 64bits.

Does not have the same problem with Opera 47, Vivaldi 1.11 and Chrome 60 (all in Linux)  where it uses the code: 192, but shows a different code from MacOS X El Capitan with Google Chrome where it uses the code: 186.
