### ISSUE TITLE
No support for "Umlaut"

### ISSUE THREAD

**Issue by MarcoHengstenberg** [wesbos/keycodes#22]
I just tried the tool and it seems there is no support for the German "Umlaut":

namely: ä, ö and ü

All three gave me zeros.

**Comment by wesbos** [comment]
Is this a key on the german keyboard or a modifier? If there is not keycode firing from the browser, I'm not sure how to track it.

**Comment by MarcoHengstenberg** [comment]
There's one key for each Umlaut. =)
https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/KB_Germany.svg/2000px-KB_Germany.svg.png

**Comment by jancborchardt** [comment]
This is a duplicate of https://github.com/wesbos/keycodes/issues/3

**Comment by MarcoHengstenberg** [comment]
Oops. Sorry. Should have kept my eyes open before submitting.
Shutting down now.

**Comment by jancborchardt** [comment]
Happens ;) after all it’s still an issue as well.
