### ISSUE TITLE
Missing keycode 241

### ISSUE THREAD

**Issue by thomas992** [wesbos/keycodes#222]
Alt Capslock

Used in Japanese IME to change character set to Hiragana. Check out my language learning concept http://abokado.herokuapp.com/

I was thinking of adding keyboard shortcuts for some neat features. I want to add a shortcut to write the word in a sentence. I'm hoping people will volunteer vocabulary and data like this to make a more feature complete site :)

**Comment by palashmon** [comment]
Hi, thanks for reporting this. The site has been updated. Could you please check if the issue still exists and let us know your response. Closing this for now.

Regards!
