### ISSUE TITLE
Missing keycode 152

### ISSUE THREAD

**Issue by vaguerant** [wesbos/keycodes#225]
My keyboard is nominally meant for Android, it's a "Rapoo BT Ultra-slim Keyboard for Android". I'm actually using it on a Raspberry Pi Model 3, in Chromium.

The key has a symbol of a padlock on it. I've actually never used this keyboard on an Android device, so I'm not sure what it does, but I assume it locks the screen. On my old (dead) Windows machine, I used some tool to remap it as PrintScr (on the Windows-side) because the keyboard doesn't have one of its own and it's so damn useless. On Windows and the Pi, the key does absolutely nothing.

**Comment by palashmon** [comment]
Hi, thanks for reporting this. The site has been updated. Could you please check if the issue still exists and let us know your response. Closing this for now.

Regards!
