### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by billmei** [wesbos/keycodes#226]
Hi! I'm looking to fork this project and am wondering if you can add a LICENSE?

Thanks!

**Comment by palashmon** [comment]
Hi @wesbos, should we add a simple MIT license to this project? I can add that in few minutes. Just wanted to discuss it once with you?

Ref: https://choosealicense.com/

Regards!

**Comment by wesbos** [comment]
Yeah adding a MIT License is a good idea :)

**Comment by palashmon** [comment]
I have added the LICENSE
