### ISSUE TITLE
key combinations would be nice, such as Shift+a to represent capitals and line breaks

### ISSUE THREAD

**Issue by beatefalconer** [wesbos/keycodes#229]
Could you add key combinations so that we can get the capital letters and things like hidden line breaks (shift enter)?
a: 97
Shift+a = A: 65

**Comment by DennisJamin** [comment]
What you are talking about is the charCode property which represents the unicode value of the pressed key, which is considerably different to the keyCode property, a mistake easily (and often) made 😄 

Check out https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode and https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by palashmon** [comment]
Closing this for now, but we might add this feature in future release.

Regards!
