### ISSUE TITLE
Azerty keymaps (Linux)

### ISSUE THREAD

**Issue by Eiyeron** [wesbos/keycodes#23]
Hello.
I'm using ArchLinux with Firefox 42.0 and with normal FR keyboard (AZERTY without dead keys IIRC) mapping and here are the unknown keybindings:
- '<' (between Shift and W) key : 60
- '²' (next from &/1) : 0 (?)
- ')' (next from à/0) : 169
- '=' (next from ')') :  61
- '^' (next to 'p') : 0 (?)
- '$' (next from '^') : 164
- 'ù' ('next from 'M') : 165
- '*' ('next from 'ù') : 170
- ';' ('next from ',') : 59
- '!' ('next from ';') : 161

have a nice day!

**Comment by Eiyeron** [comment]
Here are the the name errors on the same config but on Chromium 46.0

- '²' : erroneously says "single quote"
- '^' : erroneously says "open bracket" for both of them
- '$' : erroneously says "semi-colon"
- 'ù' : erroneously says "grave accent
- '*' and '<' : erroneously says "back-slash"
- ';' : erroneously says "period"
- ':' : erroneously says "forward slash"
- '!' : Mssing key : 223

**Comment by wesbos** [comment]
Hrm - not sure how to handle these multi-langauge keyboards - they same key codes are different keys on different keyboards

**Comment by KeitIG** [comment]
Some hints http://stackoverflow.com/questions/10531977/key-code-for-common-characters-on-international-keyboards

Bure care about https://code.google.com/p/chromium/issues/detail?id=300475

**Comment by palashmon** [comment]
Closing this issue for now. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this or open a new one. We'll gladly take a look again!
