### ISSUE TITLE
event.key blank for Spacebar

### ISSUE THREAD

**Issue by aashutoshrathi** [wesbos/keycodes#239]

**Comment by wesbos** [comment]
It's not blank, but it's showing a space character. Maybe we should add some logic to show that it's a an actual space character? 

`window.addEventListener('keyup', (e) => { console.log("'" + e.key + "'")})` 

→ `' '`

**Comment by palashmon** [comment]
Also, using browsers console you can test this:

```js
String.fromCharCode(32)
> return " "
``

**Comment by wesbos** [comment]
we can do this :)
