### ISSUE TITLE
will you consider about adding the reverse feature?

### ISSUE THREAD

**Issue by hanzichi** [wesbos/keycodes#240]
the repo is great, but sometimes I need to know the key from keycode, will consider about this feature?

thanks

**Comment by palashmon** [comment]
Hi, thanks so much for your appreciation.

Regarding your query, we will like to keep things simple and just do what this site is meant to do, get the codes from the pressed key at the moment. But we might consider this for future updates if there are enough upvotes on this case.

Also in the meantime, if someone wants to go ahead and create a new site based on this feature than they are more than welcome.

Regards!

**Comment by s-a** [comment]
👍 need this too.

**Comment by wesbos** [comment]
Could be worth popping up a table of all the codes we have in the json file...
