### ISSUE TITLE
No Scandinavian letters

### ISSUE THREAD

**Issue by aronhoyer** [wesbos/keycodes#241]
Seems like the keymap is wrong or something.

<img width="953" alt="screen shot 2018-08-10 at 22 52 04" src="https://user-images.githubusercontent.com/10201831/43981339-bc93b270-9cf1-11e8-8ab0-3515f1a1ed39.png">

Edit: I'm a poopy-head who doesn't know what he's talking about. At all. Evidently all key codes are mapped to what appears to be US keyboard. Right?

**Comment by wesbos** [comment]
I'm not sure how this works actually.

Does the event.key not show you?

**Comment by aronhoyer** [comment]
event.key shows the correct key, I just goofed and looked only at the event.code

**Comment by palashmon** [comment]
Closing this for now. Please re-open if needed.
