### ISSUE TITLE
Suggest to move to https://

### ISSUE THREAD

**Issue by 185driver** [wesbos/keycodes#243]
With the way recent browser versions complain about insecure `http://` connections, might it be a good idea to move this nifty resource to `https://`? Just a suggestion.

**Comment by wesbos** [comment]
good idea -just migrating the domain to a new registrar and I'll flip on cloudflare after that

**Comment by Khaledgarbaya** [comment]
Netlify can be a nice hosting solution for this also

**Comment by wesbos** [comment]
its already hosted on github pages so there isn't a need to move it anywhere

**Comment by wesbos** [comment]
okay everything is moved to https :D
