### ISSUE TITLE
ABNT semicolon key

### ISSUE THREAD

**Issue by lfbittencourt** [wesbos/keycodes#25]
For the record: pressed colon/semicolon key and saw `59` followed by `huh? Let me know what browser and key this was`. Browser is Firefox 42 and keyboard layout is brazilian portuguese ABNT.

**Comment by wesbos** [comment]
Thank you - can you add it to scripts.js and submit a PR?

**Comment by wesbos** [comment]
Added

**Comment by lfbittencourt** [comment]
Sorry, @wesbos. Had no time to submit the PR :-(
