### ISSUE TITLE
 Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by Sadovikow** [wesbos/keycodes#257]
Hello! Error on https://keycode.info/

scripts.js?v=10112018:190 Uncaught TypeError: Cannot read property 'appendChild' of null
    at scripts.js?v=10112018:190

**Comment by palashmon** [comment]
Hi, which browser did you tested this on?

**Comment by Sadovikow** [comment]
Chrome

**Comment by palashmon** [comment]
Not able to reproduce the issue. Closing this for now. Please re-open if needed.
