### ISSUE TITLE
Backticks broke IE11

### ISSUE THREAD

**Issue by jmpresso** [wesbos/keycodes#259]
The backticks are breaking IE11. I see a couple of examples here:

https://github.com/wesbos/keycodes/blob/gh-pages/scripts.js#L188

**Comment by palashmon** [comment]
Closing this as we are not adding fix for IE11 anymore, as Microsoft will stop support for Internet Explorer 11, Legacy Edge by 2021. 

For more info: https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666
