### ISSUE TITLE
No support for the key  'PrintScreen'

### ISSUE THREAD

**Issue by M69W** [wesbos/keycodes#263]
Hi, I have a issue about your site [https://keycode.info/](https://keycode.info/)
When I click the key 'PrintScreen',
It's don't show me the result what I want but nothing.
it's should be show me something:
Example:
`code:"PrintScreen",`
`key: "PrintScreen",`
`keyCode: 44,`
`type: "keyup",`
`which: 44...`

And you could test the keyboard in [this site](https://unixpapa.com/js/testkey.html) if you don't understand what I said.
the key "PrintScreen" has keyup event only.
the  scripts.js in [here](https://github.com/wesbos/keycodes/blob/gh-pages/scripts.js#L238) just have one key function is `body.onkeydown`, 
 If it add the function `body.onkeyup` it's will show me something when I click the key "PrintScreen".

anyway, 
Your site is very usefull for me,
Thank you.

**Comment by darthvader1925** [comment]
As of 2020, this still has not been fixed.

**Comment by wesbos** [comment]
as of 2020 it's fixed!

**Comment by darthvader1925** [comment]
I have just tried it, and hasn't worked.

**Comment by wesbos** [comment]
I just merged it, give it a sec

**Comment by darthvader1925** [comment]
It now works!

**Comment by M69W** [comment]
perfect job!
thanks.
