### ISSUE TITLE
Missing keycodes

### ISSUE THREAD

**Issue by LuizFritsch** [wesbos/keycodes#266]
Missing keycode for some brazillian characteres like " ` ", " ~ ", " ´ ", " ^ ".

**Comment by BhavyaSingh2611** [comment]
hi these keycodes are already present you can check on keycode.info

**Comment by LuizFritsch** [comment]
tried and got event.key = dead

**Comment by RubenVerg** [comment]
that's because ur kb uses dead keys, if you type `\`` followed by `a` you get `à`. that's a dead key.
