### ISSUE TITLE
change the cursour to pointer 

### ISSUE THREAD

**Issue by Aayush9029** [wesbos/keycodes#269]
it's not a huge issue but it would be awesome of the cursor changed to pointer while hovering (event.key, event.location....)

**Comment by palashmon** [comment]
Hi, thanks for your filing this issue. Just wanted to mention that `cursor: pointer` css property mainly indicates a link, as mentioned in [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#Keyword%20values) docs also. But the four divs here for all main events are not actually links but a card container. Only text like `(?)` next to event.location and `(deprecated)` text next to event.which are links and they already have `cursor: pointer` styling, added by the browser as a default behaviour. I hope that makes sense.

**Comment by Aayush9029** [comment]
Thanks a lot for the "feedback", that does make a lot of sense. Do you think letting users copy the key code by double clicking the numbers is a good idea?

**Comment by palashmon** [comment]
Yes, that can be a nice utility feature. I will try to look into this on weekend.

**Comment by Aayush9029** [comment]
<HTML>
... onclick = 'copy()' / >
</HTML>

function copy(){
document.execCommand("copy");
}
