### ISSUE TITLE
keycode Clone hijacked localhost port 5500?

### ISSUE THREAD

**Issue by dbolesta** [wesbos/keycodes#276]
I'm sure this is the wrong place to post this, but I am very confused and have no idea where else to ask.

I recently made a pull request to this repository, and in doing so cloned it to my local machine. I have since deleted all traces of the repository on my machine.

However, my localhost port 5500 (which happens to be the default port of the Live Server extension for VSCode) now always sends me to the keycodes website. This happens even if I am completely offline (wifi off), and if VSCodes LiveServer is disabled / uninstalled. No matter what, http://127.0.0.1:5500/ will send me to the keycodes website.

Again, as far as I can tell, no traces of this repository are on my machine anymore. I've tried restarting my machine (macbook), uninstalling Live Server, scraping my machine for traces of this repository, [killing port 5500 from the terminal](https://stackoverflow.com/questions/3855127/find-and-kill-process-locking-port-3000-on-mac), but http://127.0.0.1:5500/ still sends me to the keycodes site.

I am at an absolute loss and am not sure what to do. Not only is it super inconvenient to lose the LiveServer default port, but I don't want a port to be constantly serving a site, and want to know how it is even showing this site when all the files have been deleted.

Any advice is appreciated.

**Comment by wesbos** [comment]
You likely have the service worker serving up the cached version. Happens a lot on local development. Just open the application tab on Dev tools and unregister / remove it

**Comment by dbolesta** [comment]
That was exactly it. Thank you so much Wes. I can add this to the long list of things I have learned from you (I was mostly upset because this was preventing me from continuing your JS30 course :))
