### ISSUE TITLE
Trying to do the thing you did

### ISSUE THREAD

**Issue by UgurBasural** [wesbos/keycodes#280]
Hello. In this project of yours, you was able to recognize the key events even though users didn't even have to click to the page. How did you accomplish this? I am asking this because I am currently working on a similar functionality. In meantime, I am handling such events by using tabindex attritube in the outermost div. Any help would be appreciated, thanks!

**Comment by palashmon** [comment]
This is very simple using `body.onkeydown` event handler. You can also review the full code in this repo.
