### ISSUE TITLE
Doesn't work in IE

### ISSUE THREAD

**Issue by sergiubologa** [wesbos/keycodes#284]
My main use case for using this tool is to find the names and codes of different keys in IE11, which most of the time are different than in other browsers, but it seems like this tool is not designed to work in IE at all. 

Was previously supported and not anymore or what's the reason for not supporting IE?

**Comment by BuZZ-dEE** [comment]
As an alternative you can use https://crisbnp.github.io/keycode-generator/

**Comment by palashmon** [comment]
Hi, what do you mean by "_Doesn't work_"? What is the current behaviour? What is the expected behaviour? Share some examples, images to explain the issue better. Thanks!

**Comment by sergiubologa** [comment]
> Hi, what do you mean by "_Doesn't work_"? What is the current behaviour? What is the expected behaviour? Share some examples, images to explain the issue better. Thanks!

Well, seems like the styles are not loaded properly and when pressing a key nothing happens. Here's a demo where I press several keys and the app doesn't do anything.
![keycodes-ie](https://user-images.githubusercontent.com/10432669/88143013-2f5dd900-cbff-11ea-87a9-88230d9e6837.gif)

And the console looks like this:
![image](https://user-images.githubusercontent.com/10432669/88143091-50262e80-cbff-11ea-89b3-89b5049df729.png)

**Comment by palashmon** [comment]
Closing this as we are not adding fix for IE11 anymore, as Microsoft will stop support for Internet Explorer 11, Legacy Edge by 2021. 

For more info: https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666
