### ISSUE TITLE
Space character copying

### ISSUE THREAD

**Issue by OscarGlo** [wesbos/keycodes#287]
When pressing the space bar, clicking on the `event.key` box to copy the character puts "(Space character)" in the clipboard instead of an actual space character.

![image](https://user-images.githubusercontent.com/32545701/85555689-72d81e00-b626-11ea-830e-3049674b608c.png)

**Comment by manInit** [comment]
#289 
i created pull request

**Comment by palashmon** [comment]
PR merged. Closing this now.
