### ISSUE TITLE
Display .altKey .ctrlKey .metaKey .shiftKey bools of event

### ISSUE THREAD

**Issue by raphaelschaad** [wesbos/keycodes#290]
<img width="1944" alt="CleanShot 2020-09-17 at 13 53 18@2x" src="https://user-images.githubusercontent.com/439447/93466862-2e8ab000-f8ed-11ea-9671-54230a1a061e.png">

**Comment by TroyWolf** [comment]
:+1: This is a simple and useful tool. Thanks, Wes! Within 30 seconds of using it, I wanted it to also tell me when `ctrlKey` and `metaKey` are `true`. I know the correct response is to create a PR, and I might do that. In the meantime, this is me voting this idea up.

**Comment by wesbos** [comment]
its coming!

**Comment by mikob** [comment]
@wesbos any updates on this?

**Comment by wesbos** [comment]
almost ready! 


<img width="2212" alt="image" src="https://user-images.githubusercontent.com/176013/159538835-0f911253-f6d1-4ded-a6f4-4a9a5b7b0a14.png">

**Comment by wesbos** [comment]
done!
