### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by Sainan** [wesbos/keycodes#293]
When a German user presses escape on keycode.info, it says "Flucht" which is a literal translation of "to escape", which is very much wrong, but I couldn't figure out from the code provided here in this repository how it comes to say that.

**Comment by wesbos** [comment]
Is it under the key part? If so that is what the browser reports. It’a not part of this project to handle translations

**Comment by Sainan** [comment]
![image](https://user-images.githubusercontent.com/63328889/101282024-d7e98f80-37d2-11eb-96d5-8e8a62251649.png)

I just figured Google would've gotten a better translation. O.o
