### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by Harsh-Uppal** [wesbos/keycodes#299]
Just a fun little feature for a website.

**Comment by palashmon** [comment]
Actually, we already have a dark mode but it is based on if you have enabled dark mode on your operating system or not. We will try to add a button maybe in future to toggle that.

**Comment by palashmon** [comment]
UPDATE: This issue is fixed now. Thanks to @poirierlouis 🎉 
Please clear the cache once, if you are not seeing the new button in the top-right corner to toggle the theme.
Thanks!

**Comment by palashmon** [comment]
Hi @wesbos, just wanted to let you know that we have a new dark-light theme toggle button on the site now in the top-right corner.

**LIGHT MODE:**

![image](https://user-images.githubusercontent.com/14850464/126741027-0a80545c-7b9b-475f-99cf-de665c6d5c91.png)


**DARK MODE:**

![image](https://user-images.githubusercontent.com/14850464/126741110-fea52ea7-9095-4f23-9417-75626a28449a.png)

Hope it is fine!
