### ISSUE TITLE
Missing keycode 60

### ISSUE THREAD

**Issue by MiguelAngelLV** [wesbos/keycodes#30]
I use Elementary OS and Firefox.

I press <

**Comment by wesbos** [comment]
Thanks for reporting it. 

This one needs a key of `60` added with the value `<`. 

@danielmdesigns want this one?

**Comment by danielmdesigns** [comment]
Aweomse! I'll give it a shot and holler if I have any issues. Thanks!

**Comment by wesbos** [comment]
:santa:

**Comment by MiguelAngelLV** [comment]
It works! :dancers:
