### ISSUE TITLE
Missing keycode 230

### ISSUE THREAD

**Issue by ksenzee** [wesbos/keycodes#41]
GNOME Compose key. This is mappable to any key on the keyboard (https://help.gnome.org/users/gnome-help/stable/tips-specialchars.html.en). In my case, I have it mapped to Caps Lock.

OS: Ubuntu
Browser: Chrome

Note that it shows up as 0 in Firefox/Ubuntu.

**Comment by wesbos** [comment]
Thanks a ton for reporting it. Will map key `230` to `GNOME Compose Key`
