### ISSUE TITLE
Missing keycode 193

### ISSUE THREAD

**Issue by valterlima** [wesbos/keycodes#62]
OS: Microsoft Windows 7 Professional
6.1.7601 Service Pack 1 Build 7601
LENOVO 3254H4P
Keyboard: PT-BR ABNT2

[Keyboard pic](http://mlb-s1-p.mlstatic.com/teclado-lenovo-thinkpad-t530-x230-t430-w530-0c01927-04x1244-511601-MLB20352111576_072015-F.jpg)

I pressed the button next to arrow keys with "?/°" characters.

**Comment by wesbos** [comment]
Awesome- want to send in a PR?
