### ISSUE TITLE
Missing keycode 172

### ISSUE THREAD

**Issue by theblackwidower** [wesbos/keycodes#74]
Tell me what key it was or even better, submit a Pull request!

Logitech K360, Fn-F1, Google Chrome

Answer your question?

**Comment by wesbos** [comment]
What key was it? F1?

**Comment by theblackwidower** [comment]
I pressed the Fn key, held it down, and then pressed the F1 key. 

See, the Fn key is what some people call a 'modifier' key. It 'modifies' the function of other keys.

I'm pretty sure this is keyboard-specific. So you might want to Google the K360. The button's image appears to be: House. But no matter how many times I press it, I never see a drug-addicted doctor being rude to his patients. So I don't know what it does.

Oh, not sure if it's relevant, but I'm running Fedora 23.
