### ISSUE TITLE
Missing keycode 229

### ISSUE THREAD

**Issue by robert-denney** [wesbos/keycodes#79]
Tell me what key it was or even better, submit a Pull request!

This is alt+e on OSX in Chrome

I'm figuring it out myself. It's how it tries to add accents to your characters for you

**Comment by palashmon** [comment]
**Keycode:** 229
**String created:** `String.fromCharCode(229)` === `å`

**Comment by palashmon** [comment]
Hi, thanks for reporting this. The site has been updated. Could you please check if the issue still exists and let us know your response.

Regards!
