### ISSUE TITLE
Missing keycode 172

### ISSUE THREAD

**Issue by Andreas-Hjortland** [wesbos/keycodes#80]
The keycode 172 is the pipe `|` on Norwegian keyboard layouts, but I am unsure what it is on American keyboards. It is the key which is left of the `1` key (it is sometimes used to toggle the console in games).

**Comment by pawo2500** [comment]
On my keyboard it's "Home page" shortcut, it opens the browser or goes to home page on current tab.
Key: Fn+F9
Browser: Chrome 49
OS: Win 8.1
Keyboard: X2 Mirage (US layout)
Input layout: Polish (programmers)
