### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by anthonyjh** [wesbos/keycodes#95]
The values for the key strokes were actually hardcoded into the script. This should not be the case, you should be using event.keyCode to pull the actual value of the key being pressed, or hard code it correctly using something like this http://www.asciitable.com/

**Comment by wesbos** [comment]
Not sure I follow -  the point of this site is to line up the event.keyCode number with the keyboard key that was pressed. 

We're maintaining a list of the keys and the codes they are associated.

**Comment by anthonyjh** [comment]
Well it looks like your script.js is only accounting for lower-case letters. What would it display for upper-case? And why do the num-pad number codes differ from the number key codes?

**Comment by wesbos** [comment]
These are for specific keys on your keyboard, not ascii codes. There is no difference between the lowercase uppercase keys. The num pad is a separate set of keys, thus they have different keycodes.

**Comment by anthonyjh** [comment]
I see, ok that makes sense. A friend was trying to use your keycodes.info site to test for correct values coming back for something he was programming and it was different, that is why I was curious as to how this was working. Thanks for the clarification!

**Comment by wesbos** [comment]
Ahh I see - glad it's clarified :)
